package common;

public class Lyrics {
    private Lyrics() {}
    public static String[] getLyrics() { return lyrics; }
    private static String lyrics[] = {
            "Yeah- Yeah- Yeah- Yeah- Yeah-",
            "Come and be my love, Come and be my love baby",
            "Yeah- Yeah- Yeah- Yeah- Yeah-",
            "Come and be my love, Come and be my love baby",
            "I stand still with my head full of thoughts",
            "Don’t know if I’m doing the right thing",
            "Yeah- Yeah- Yeah- Yeah-",
            "Well, whatever",
            "NO- NO- NO- NO-",
            "I must have gone crazy",
            "My name is TZUYU",
            "Should I just come up and say hi",
            "This is my number",
            "Should I hand a note and run",
            "Yeah- Yeah- Yeah- Yeah-",
            "What should I do",
            "NO- NO- NO- NO-",
            "Now’s the time",
            "Girl you can do it",
            "Our eyes are meeting",
            "Love is Timing",
            "If I miss it I’d regret it",
            "Love is Coming Coming Take a little more courage",
            "Don’t hesitate anymore",
            "Though it may seem weird, I can’t help it, cuz I fell for you",
            "You’re my heart shaker-shaker",
            "Don’t wanna lose you",
            "You’re my heart shaker-shaker",
            "What should I do",
            "I won’t wait like a fool",
            "I’ll say that I fell for you",
            "That I like you, that I miss you all day long",
            "Would you be my love",
            "Cuz I fell for you",
            "Manage that facial expression, make it look natural",
            "Talk like Cool- Cool No need to get nervous",
            "Yeah- Yeah- Yeah- Yeah-",
            "Pay close attention and focus",
            "NO- NO- NO- NO-",
            "What should I do, I can’t look straight",
            "Now’s the time",
            "Girl you can do it",
            "Our eyes are meeting",
            "Love is Timing",
            "If I miss it I’d regret it",
            "Love is Coming Coming Take a little more courage",
            "Don’t hesitate anymore",
            "Though it may seem weird, I can’t help it, cuz I fell for you",
            "You’re my heart shaker-shaker",
            "Don’t wanna lose you",
            "You’re my heart shaker-shaker",
            "What should I do",
            "I won’t wait like a fool",
            "I’ll say that I fell for you",
            "That I like you, that I miss you all day long",
            "Would you be my love",
            "Cuz I fell for you",
            "In the end you’ll also be wanting me. You’ll end up loving me",
            "I hope so dearly for you to be like me",
            "Don’t hesitate, approach first",
            "Say your love, don’t hold back",
            "Come, baby be my, be my, be my love",
            "Come baby, bae- bae- bae- bae-",
            "Though it may seem weird, I can’t help it, cuz I fell for you",
            "You’re my heart shaker-shaker",
            "Don’t wanna lose you",
            "You’re my heart shaker-shaker",
            "What should I do",
            "I won’t wait like a fool I’ll say that I like you",
            "That I like you, that I miss you all day long",
            "That I love you",
            "That I fell for you",
            "Yeah- Yeah- Yeah- Yeah- Yeah-",
            "You are mine (Be mine)",
            "Yeah- Yeah- Yeah- Yeah- Yeah-",
            "I’ll say that I like you",
            "Cuz I fell for you"
    };
}
